enum CartActionType {
  CART_REQUEST = 'CART_REQUEST',
  CART_SUCCESSED = 'CART_SUCCESSED',
  CART_FAILED = 'CART_FAILED',
  POST_ADD_PRODUCT_REQUEST = 'POST_ADD_PRODUCT_REQUEST',
  POST_ADD_PRODUCT_SUCCESSED = 'POST_ADD_PRODUCT_SUCCESSED',
  POST_ADD_PRODUCT_FAILED = 'POST_ADD_PRODUCT_FAILED',
  POST_PAYMENTS_REQUEST = 'POST_PAYMENTS_REQUEST',
  POST_PAYMENTS_SUCCESSED = 'POST_PAYMENTS_SUCCESSED',
  POST_PAYMENTS_FAILED = 'POST_PAYMENTS_FAILED',
  DELETE_CART_PRODUCTS_REQUEST = 'DELETE_CART_PRODUCTS_REQUEST',
  DELETE_CART_PRODUCTS_SUCCESSED = 'DELETE_CART_PRODUCTS_SUCCESSED',
  DELETE_CART_PRODUCTS_FAILED = 'DELETE_CART_PRODUCTS_FAILED',
}

export default CartActionType;
