enum CartActionType {
  CART_REQUEST = 'CART_REQUEST',
  CART_SUCCESSED = 'CART_SUCCESSED',
  CART_FAILED = 'CART_FAILED',
  DELETE_CART_PRODUCTS_REQUEST = 'DELETE_CART_PRODUCTS_REQUEST',
  DELETE_CART_PRODUCTS_SUCCESSED = 'DELETE_CART_PRODUCTS_SUCCESSED',
  DELETE_CART_PRODUCTS_FAILED = 'DELETE_CART_PRODUCTS_FAILED',
}

export default CartActionType;
