enum ProductDetailsActionType {
  PRODUCTDETAILS_REQUEST = 'PRODUCTDETAILS_REQUEST',
  PRODUCTDETAILS_SUCCESS = 'PRODUCTDETAILS_SUCCESS',
  PRODUCTDETAILS_FAILED = 'PRODUCTDETAILS_FAILED',
}

export default ProductDetailsActionType;
