enum ProductDetailsActionType {
  PRODUCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_REQUEST',
  PRODUCT_DETAILS_SUCCESSED = 'PRODUCT_DETAILS_SUCCESSED',
  PRODUCT_DETAILS_FAILED = 'PRODUCT_DETAILS_FAILED',
  POST_ADD_PRODUCT_REQUEST = 'POST_ADD_PRODUCT_REQUEST',
  POST_ADD_PRODUCT_SUCCESSED = 'POST_ADD_PRODUCT_SUCCESSED',
  POST_ADD_PRODUCT_FAILED = 'POST_ADD_PRODUCT_FAILED',
}

export default ProductDetailsActionType;
