enum ProductDetailsActionType {
  PRODUCTDETAILS_REQUEST = 'PRODUCTDETAILS_REQUEST',
  PRODUCTDETAILS_SUCCESSED = 'PRODUCTDETAILS_SUCCESSED',
  PRODUCTDETAILS_FAILED = 'PRODUCTDETAILS_FAILED',
}

export default ProductDetailsActionType;
