enum PurchasedProducutsActionType {
  GET_PURCHASED_PRODUCTS_REQUEST = 'GET_PURCHASED_PRODUCTS_REQUEST',
  GET_PURCHASED_PRODUCTS_SUCCESSED = 'GET_PURCHASED_PRODUCTS_SUCCESSED',
  GET_PURCHASED_PRODUCTS_FAILED = 'GET_PURCHASED_PRODUCTS_FAILED',
}

export default PurchasedProducutsActionType;
