enum ProductListActionType {
  PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST',
  PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS',
  PRODUCT_LIST_FAILED = 'PRODUCT_LIST_FAILED',
}

export default ProductListActionType;
